# Définition d'un bloc serveur — équivalent d'un VirtualHost Apache
server {

    # Port d'écoute — Nginx écoute les requêtes HTTP sur le port 80
    listen 80;

    # Nom du serveur — localhost pour le développement
    # En production ce sera ton nom de domaine ex: monsite.com
    server_name localhost;

    # Dossier racine — pointe vers ton dossier public/
    # Seul ce dossier est accessible depuis le navigateur
    # src/, vendor/, tests/ ne sont jamais exposés
    root /var/www/html/public;

    # Fichier par défaut — index.php est le point d'entrée de l'API
    index index.php;

    # Gestion de toutes les URLs entrantes
    location / {
        # Cherche dans l'ordre :
        # 1. Un fichier qui correspond exactement à l'URL ($uri)
        # 2. Un dossier qui correspond ($uri/)
        # 3. Sinon redirige tout vers index.php — c'est ce qui permet
        #    le routing : /users/1 → index.php qui gère la route
        try_files $uri $uri/ /index.php$is_args$args;
    }

    # Gestion des fichiers PHP — toute URL se terminant par .php
    location ~ \.php$ {

        # Transfère la requête à PHP-FPM
        # "php" = nom du service dans docker-compose.yml
        # Docker résout automatiquement "php" en adresse IP interne
        # 9000 = port par défaut de PHP-FPM
        fastcgi_pass php:9000;

        # Fichier PHP par défaut si aucun fichier n'est spécifié
        fastcgi_index index.php;

        # Indique à PHP-FPM le chemin complet du fichier à exécuter
        # $document_root = valeur de "root" défini plus haut
        # $fastcgi_script_name = nom du script demandé
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

        # Inclut les paramètres FastCGI standards de Nginx
        # (variables comme REQUEST_METHOD, QUERY_STRING, etc.)
        include fastcgi_params;
    }
}